[font]
size=24

[font.normal]
family = "0xProto Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "w"
mods = "Command"

[window]
opacity = 1
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

